# Generated by Django 2.0.8 on 2018-08-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'blog category', 'verbose_name_plural': 'blog categories'},
        ),
    ]
