# Generated by Django 2.0.8 on 2018-09-19 05:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('blog', '0005_auto_20180827_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='hero_body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='hero_title',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
