# Generated by Django 2.0.8 on 2018-08-29 07:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featre_section_1_page',
            field=models.ForeignKey(blank=True, help_text='Feature 1 to be displayed in homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featre_section_2_page',
            field=models.ForeignKey(blank=True, help_text='Feature 1 to be displayed in homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_section_1',
            field=models.CharField(default=1, help_text='Title for feature 1', max_length=520),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_section_2',
            field=models.CharField(default=1, help_text='Title for feature 1', max_length=520),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
