# Generated by Django 2.0.8 on 2018-09-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_socialitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialitems',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
